### PR TITLE
Allow passing a url path to remove from the original filename

### PR DESCRIPTION
**Pull request by pcruz7**

### CODE REVIEW

**Comment by HashanP** [comment]
Hi! Sorry, can I just ask what is the point of this modification? Is it to change the name under which the template is registered, or something else?

**Comment by pcruz7** [comment]
Hi ! Yes it is. I ran into an "issue" where i needed to use the same template in both server and cliente side. I had the following partial in there:

```
{> "path/to/partial" /}
```

But since it was registering just "partial", dust could not find it. With this change if we pass /my/home/project/ unto the transform we can turn /my/home/project/path/to/partial.dust into path/to/partial, which is just what we need to render the correct partial.

Thoughts?

**Comment by HashanP** [comment]
Okay, so here's what I've done. I've changed it so templates are registered relative to wherever browserify is called. So basically if you run browserify at `/random/path`, and your trying to access a template at `/random/path/hi.dust`, you just have to put:
```
{> "hi.dust"}
```
I decided to add the `.dust`, because I thought that would create more consistency, since when you `require()` the partial, you also have to put `.dust`. I've published the lastest verison of `browserify-dustjs` as a beta on NPM so to get it: 
```
npm install browserify-dustjs@beta
```
If you can tell me if it works for you, then I can release it as a proper version.

**Comment by pcruz7** [comment]
Nop, that won't work. I need it to work in both sides - client and server - and in the server the paths are set as such: `{> "random/path/server" /}` and not `{> "server.dust" /}`. 

The server is the one I need to be compliant with not the client :)

**Comment by HashanP** [comment]
Okay I've published a new version. You don't have to put `.dust`, and I removed `path.basename`, so if you run browserify as `/random/`, to access `/random/path/hi`, you do `path/hi`. If you, however, want all paths to be relative to `/` you can specify, an option called `root` e.g. `{root: "/"}`. If you do this, then you will have to put `random/path/hi`. Or conversely you could specify `root` to be `/random/path/` and then all you would have to do is put `hi`. The version is available at `browserify-dustjs@beta`. Tell me if it works. :smiley:

**Pull request merged**
